- name: Install k3s
  shell: |
    curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure k3s is running
  systemd:
    name: k3s
    state: started
    enabled: yes

- name: Create .kube directory
  file:
    path: /home/pi/.kube
    state: directory
    owner: pi
    group: pi
    mode: '0755'

- name: Copy kubeconfig
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /home/pi/.kube/config
    remote_src: yes
    owner: pi
    group: pi
    mode: '0644'
