name: Deploy Grafana and Prometheus

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy namespace
        run: |
          kubectl apply -f grafana/namespace.yaml

      - name: Deploy Secrets
        env:
          ADMIN_USER: ${{ secrets.ADMIN_USER }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        run: |
          chmod +x grafana/secrets.sh
          ./grafana/secrets.sh

      - name: Deploy Components
        run: |
          chmod +x grafana/deploy.sh
          cd grafana
          ./deploy.sh

      - name: Verify deployment
        run: |
          kubectl get pods -n backstage